### ISSUE TITLE
git commits

### ISSUE THREAD

**Issue by graiola** [graiola/wolf_ylo2_interface#10]
Hi @elpimous ,

I noticed that my commits get overridden by your commits. Are you merging my commits or just force pushing your commits on top? It makes difficult for me to work on it otherwise.

**Comment by elpimous** [comment]
Oh, sorry... It's my fault for sure..
i made error on controller branch ?

**Comment by graiola** [comment]
my commit just got lost in the git history for some reasons. I can merge your last commit with mine and push it again.

**Comment by graiola** [comment]
I can not merge your commit because it was force pushed over mine.

I am going to use your last commit, but please if I create new commits, merge with them otherwise I lose track of what's going on :(

**Comment by elpimous** [comment]
Again, sorry ! I keep in mind, no : never force, but merge.

**Comment by graiola** [comment]
I am going to clean some branches, from now on we can develop on `devel` and create new branches to add features, for example I am going to create a branch `impedance_controller` for the new controller or a branch like `fix_something` for the branches that implement a fix.
