### ISSUE TITLE
myahrs drivers

### ISSUE THREAD

**Issue by graiola** [graiola/wolf_ylo2_interface#11]
As it is now in the `devel` branch, it is not possible to compile myahrs drivers because it is a catkin package within a catkin package. I would suggest to either:
- move it outside
- integrate it inside `wolf_ylo2_interface` as we did with the moteus drivers.

Also, it could be better to integrate the read function for the imu directly in our hardware interface, instead of reading through a ROS topic.

**Comment by elpimous** [comment]
Sure. I totally agree with you.
I'll try to integrate, same way that moteus package, tonight.

**Comment by graiola** [comment]
I am going to start a new branch named `imu_integration`, also, be careful that I merged some branches into devel and removed them, so be sure to `git fetch` before working on it :)

**Comment by elpimous** [comment]
👌

**Comment by graiola** [comment]
I pushed some modifications in `imu_integration`, could you please (when you are able to) try if it works on your side? Thanks.

**Comment by elpimous** [comment]
Hi, working  !! However, error in frame : 
rviz /    world : `No transform from [world] to [trunk_imu]`

**Comment by graiola** [comment]
did you try changing this parameter?

https://github.com/graiola/wolf_ylo2_interface/blob/imu_integration/launch/test_hardware.launch#L27

**Comment by elpimous** [comment]
Sure. tested **trunk** and **trunk_imu** no success...
First, i'll integrate imu read under a function, in ylo2_robot_hw.cpp, then i'll investigate on frames, lol
