### ISSUE TITLE
motor_adapter

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf_ylo2_interface#12]
Hello, ylo2 use the **turn** type, as joint rotation. I changed it to **radians**, to fit wolf controller need.
1/ could you confirm wolf_hardware_interface legs order ? 
front left   -> (Haa, Hfe, Kfe) -> 0, 1, 2
front right -> (Haa, Hfe, Kfe) -> 3, 4, 5
back left   -> (Haa, Hfe, Kfe) -> 6, 7, 8
back right -> (Haa, Hfe, Kfe) -> 9, 10, 11

2/ using the (joint_trajectory_controller), with `roslaunch wolf_ylo2_interface test_hardware.launch`,
is this rviz interface exact with joints rotation directions ? is it using the ylo2RobotHw::read() --> **joint_position_[jj]** value ?
I say that because i have some problems to fix rotations on some joints.
Thanks @graiola

**Comment by elpimous** [comment]
when running **rostopic echo /ylo2/joint_states**, after **roslaunch wolf_ylo2_interface test_hardware.launch**
i see : 
`...
name: 
  - lf_haa_joint
  - lf_hfe_joint
  - lf_kfe_joint
  - lh_haa_joint
  - lh_hfe_joint
  - lh_kfe_joint
  - rf_haa_joint
  - rf_hfe_joint
  - rf_kfe_joint
  - rh_haa_joint
  - rh_hfe_joint
  - rh_kfe_joint`
it let me think that joints order is front left, back left, front right, back right.
Is it the order that I must into wolf ylo2 hardware ?

**Comment by elpimous** [comment]
![IMG_20221120_175818.jpg](https://user-images.githubusercontent.com/8529940/202917705-f6e66257-5ca3-4ce2-8cc7-a698c17cfc9c.jpg)

**Comment by elpimous** [comment]
![IMG_20221120_175921.jpg](https://user-images.githubusercontent.com/8529940/202917717-0580b277-2539-417e-8add-44e7f5d36ff0.jpg)

**Comment by elpimous** [comment]
I changed motors order (in motor_adapters_[] vector), and followed `/ylo2/joint_states`order.
After changing too some signs, now moving joints in real produce correct moves on rviz. cool.
Is what i see in rviz (joints indexes and their direction) the correct one for wolf final controller ?  **I think yes, but i'd like confirmation.**

**Comment by elpimous** [comment]
If yes, i'd like to test it in real, with increasing params : 
- start from 1Mn to Max
- modify in controllers internal params, min and max angles (forces will limit over angles)

can you confirm me the process to run ylo2 in real : 
- `roslaunch wolf_ylo2_interface run.launch`
- `roslaunch wolf_controller wolf_controller_bringup.launch input_device:=keyboard robot_name:=ylo2 gazebo:=false`

**Comment by elpimous** [comment]
` WARN] [1668969517.813030422]: Converting unknown joint type of joint 'floating_base_joint' into a fixed joint
[ INFO] [1668969517.814204030]: Floating joint. Not adding segment from world to trunk. This TF can not be published based on joint_states info
[ INFO] [1668969518.207098444]: --MOTEUS INITIALIZATION & RESET-> OK--
[ INFO] [1668969518.211323593]: --MOTEUS MOTORS STOPPED --------> OK--

Zeroing joints. angle_joint tolerance is < 15 degrees

[ INFO] [1668969518.213189291]: --Controleur ID : 3 ; actual position : -0.051117 ; zero target position : -0.050883 ; difference : 0.000234 ; angle error in degrees : 0.084256 degrees
[ INFO] [1668969518.214238312]: --Controleur ID : 1 ; actual position : -0.186933 ; zero target position : -0.186976 ; difference : -0.000043 ; angle error in degrees : -0.015391 degrees
[ INFO] [1668969518.215285760]: --Controleur ID : 2 ; actual position : 0.434614 ; zero target position : 0.434587 ; difference : 0.000027 ; angle error in degrees : 0.009592 degrees
[ INFO] [1668969518.216331144]: --Controleur ID : 9 ; actual position : 0.050934 ; zero target position : 0.050883 ; difference : 0.000051 ; angle error in degrees : 0.018338 degrees
[ INFO] [1668969518.217388230]: --Controleur ID : 7 ; actual position : -0.188162 ; zero target position : -0.186976 ; difference : 0.001186 ; angle error in degrees : 0.426809 degrees
[ INFO] [1668969518.218432856]: --Controleur ID : 8 ; actual position : 0.434444 ; zero target position : 0.434587 ; difference : -0.000143 ; angle error in degrees : -0.051616 degrees
[ INFO] [1668969518.219532001]: --Controleur ID : 6 ; actual position : 0.050914 ; zero target position : 0.050883 ; difference : 0.000031 ; angle error in degrees : 0.011014 degrees
[ INFO] [1668969518.220622560]: --Controleur ID : 4 ; actual position : 0.183894 ; zero target position : 0.186976 ; difference : -0.003082 ; angle error in degrees : -1.109447 degrees
[ INFO] [1668969518.221692816]: --Controleur ID : 5 ; actual position : -0.431167 ; zero target position : -0.434587 ; difference : -0.003420 ; angle error in degrees : -1.231070 degrees
[ INFO] [1668969518.222761926]: --Controleur ID : 12 ; actual position : -0.056356 ; zero target position : -0.050883 ; difference : 0.005473 ; angle error in degrees : 1.970246 degrees
[ INFO] [1668969518.223813412]: --Controleur ID : 10 ; actual position : 0.187091 ; zero target position : 0.186976 ; difference : 0.000115 ; angle error in degrees : 0.041376 degrees
[ INFO] [1668969518.224853388]: --Controleur ID : 11 ; actual position : -0.426328 ; zero target position : -0.434587 ; difference : -0.008259 ; angle error in degrees : -2.973186 degrees

[ INFO] [1668969518.225135759]: --ROBOT CALIBRATION CHECKED ----> OK--

startup_routine Done.
[ INFO] [1668969553.514355559]: Robot total mass is [10.857]
[ INFO] [1668969553.514485862]: Joint position limits set to: min=[  -1e+09   -1e+09   -1e+09   -1e+09   -1e+09   -1e+09 -1.22173   -1e+16 -2.77507 -1.22173   -1e+16 -2.77507 -1.22173   -1e+16 -2.77507 -1.22173   -1e+16 -2.77507]
max=[    1e+09     1e+09     1e+09     1e+09     1e+09     1e+09   1.22173     1e+16 -0.645772   1.22173     1e+16 -0.645772   1.22173     1e+16 -0.645772   1.22173     1e+16 -0.645772]
[ INFO] [1668969553.514564206]: Joint velocity limits set to: max=[1e+09 1e+09 1e+09 1e+09 1e+09 1e+09    20    20    15    20    20    15    20    20    15    20    20    15]
[ INFO] [1668969553.514627042]: Joint effort limits set to: max=[ 0  0  0  0  0  0 14 14 14 14 14 14 14 14 14 14 14 14]
[ INFO] [1668969553.514737713]: Robot stand-up height is [0.273481]
[ERROR] [1668969553.515663985]: hardware_interface::ImuSensorInterface not found
[ERROR] [1668969553.515710305]: Failed to initialize the controller
[ERROR] [1668969553.515736051]: Initializing controller 'wolf_controller' failed`

**Comment by elpimous** [comment]
need to work on **hardware_interface::ImuSensorInterface**  Any example I could use, to copy a bit ?

**Comment by graiola** [comment]
Hi Vincent, the leg order is corret ("lf","lh","rf","rh") and the joint order is ("haa","hfe","kfe").
For the imu interface, give a look at: https://github.com/graiola/wolf_aliengo_interface/blob/master/src/aliengo_robot_hw.cpp#L105-L119
and https://github.com/graiola/wolf_hardware_interface

**Comment by elpimous** [comment]
thanks @graiola .
the content of my actual imu publishing : 
`  seq: 2584
  stamp: 
    secs: 1668970976
    nsecs: 667800686
  frame_id: "trunk"
orientation: 
  x: -0.002464047366311073
  y: -0.022377179535257783
  z: 0.1937761023443666
  w: 0.980787445100542
orientation_covariance: [4.592449e-06, 0.0, 0.0, 0.0, 4.592449e-06, 0.0, 0.0, 0.0, 4.592449e-06]
angular_velocity: 
  x: -0.006391781671934074
  y: -0.007457078877330745
  z: -0.006391781671934074
angular_velocity_covariance: [5.895184e-06, 0.0, 0.0, 0.0, 5.895184e-06, 0.0, 0.0, 0.0, 5.895184e-06]
linear_acceleration: 
  x: 0.28252441759631036
  y: -0.052674043958634134
  z: 9.471751105913519
linear_acceleration_covariance: [0.0007199025610000001, 0.0, 0.0, 0.0, 0.0007199025610000001, 0.0, 0.0, 0.0, 0.0007199025610000001]`

**Comment by elpimous** [comment]
https://github.com/graiola/wolf_ylo2_interface/blob/31bfb3e594c747987e3d752d0ff0eee69238fe9e/src/ylo2_robot_hw.cpp#L86-L99
should be enough, as in https://github.com/graiola/wolf_aliengo_interface/blob/master/src/aliengo_robot_hw.cpp#L105-L119
correct ?

**Comment by graiola** [comment]
Yes but you need to fill the variables of the hardware interface.

**Comment by elpimous** [comment]
added those parts : https://github.com/graiola/wolf_ylo2_interface/blob/4506c404c032c55da29f0aad67e4fb3c23ce7d67/src/ylo2_robot_hw.cpp#L44-L50
no imu error, but lots of warning. When you'll have some time...
https://pastebin.com/4KuAVkn6

If no problems, i need to click to enter (as on simulation) to make ylo2 stand up, correct ?

**Comment by graiola** [comment]
The warnings `TF_REPEATED_DATA ignoring data with redundant timestamp for` are related to TF. It could be caused by two `robot_state_publisher` running and publishing at the same time...

**Comment by elpimous** [comment]
removing it seems to have removed this warning.
https://github.com/graiola/wolf_ylo2_interface/blob/ca6b01af7a3bffb8171f4b9aa6c0667c870fe377/launch/run.launch#L41

**Comment by elpimous** [comment]
Hey, @graiola ..  I'm very very near to success... excited !!!
trying to standup at low Nm (2.0). not enough for sure, but legs do what they need to standup, like in simulation... Of course, they cant stand up robot, but directions and orders are ok.
Question : i have some gitters on motors, i must play with pid, correct?
Here : https://github.com/graiola/wolf_descriptions/blob/31cfb0426fc67e9e8f08ea1c67d408f03bcdecaf/ylo2_description/params/ylo2_params.yaml#L43-L44
Last question : on rviz, the ylo2 is inverted (front = back) where can i rotate it ? urdf ?
Really impatient.....

Tested again with Nm 5.0, enough to make legs support robot, doesn't stand up correctly.
Could you check correct imu integration on ylo2 / motor_adapter .
Thanks Gennaro.

**Comment by graiola** [comment]
>Question : i have some gitters on motors, i must play with pid, correct? Here : https://github.com/graiola/wolf_descriptions/blob/31cfb0426fc67e9e8f08ea1c67d408f03bcdecaf/ylo2_description/params/ylo2_params.yaml#L43-L44 

the pid is used during standup

> Last question : on rviz, the ylo2 is inverted (front = back) where can i rotate it ? urdf ? Really impatient.....

I think it is because of the imu... are the rotations correct in rviz? I mean, if you rotate the robot along roll pitch and yaw, are they correct in rviz?

**Comment by elpimous** [comment]
Hi,
Any idea of the minimal pid I could try, to test slowly? 
No, in rviz, imu is inverted.  180°Z axis.
(left is right, up is down.)
I tried to add r, p, 3.1415 here https://github.com/graiola/wolf_descriptions/blob/31cfb0426fc67e9e8f08ea1c67d408f03bcdecaf/ylo2_description/robots/ylo2.urdf.xacro#L200
Doesn't produce result in rviz.

**Comment by elpimous** [comment]
PS, perhaps silly question.
Is it possible to slow down standup?

**Comment by graiola** [comment]
> PS, perhaps silly question. Is it possible to slow down standup?

Yes, but I have to change the code because the time is hardcoded to 5s... Can you open an issue so that I can work on it in the next days? Thank you.

**Comment by elpimous** [comment]
Humm. impossible to change imu rotation axis !!! Any idea ?
https://github.com/graiola/wolf_ylo2_interface/blob/cbf5d7427e6132bb62b099c3a830811465d15d20/src/ylo2_robot_hw.cpp#L96-L98
