### ISSUE TITLE
pcanfd

### ISSUE THREAD

**Issue by graiola** [graiola/wolf_ylo2_interface#2]
Where do I find libpcanfd.h?

**Comment by elpimous** [comment]
It is part of pcanbasic driver, from PEAK, installed on my ubuntu system.
https://www.peak-system.com/fileadmin/media/linux/files/peak-linux-driver-8.12.0.tar.gz

**Comment by graiola** [comment]
Ok I will try to install the drivers and compile on my side the code :)

**Comment by elpimous** [comment]
:) big thanks, Gennaro.

**Comment by elpimous** [comment]
Hello Gennaro,Adding rplidar A2, D435 and T265 as sensors, on Ylo2. I'll push it when finished. The imu c++ header is nearly finished, just a type function conversion problem, for now...(Posted as issue) I saw that you are working on a devel branch of ylo2_wolf_interface, cool.Tell me if I can help.. Have a nice day.

**Comment by graiola** [comment]
Hi Vincent, I think you can use the ros wrappers for D435 and T265. I am trying to compile your branch but it fails here:

https://github.com/graiola/wolf_ylo2_interface/blob/master/ylo2_moteus/src/ylo2_moteus_node.cpp#L87

**Comment by elpimous** [comment]
Thanks for the tips, looking at this, now.
Well, my package is a modification of : https://github.com/raess1/k3lso3_ros2/tree/master/k3lso_moteus
looking for error now

**Comment by elpimous** [comment]
I think this line is a bad ghost one ; remove it.

**Comment by graiola** [comment]
Regarding the cameras, you can check this repo: https://github.com/IntelRealSense/realsense-ros.
Also, there are the generated debians available through apt as ros-${ROS-DISTRO}-realsense2.
The cameras are not part of the hardware interface, instead you can use the ros wrappers and their topics directly with the ROS navigation stack, the same we are doing now in simulation with `wolf_navigation`.

**Comment by elpimous** [comment]
nice, working on this..

**Comment by elpimous** [comment]
Hello Gennaro,
just tested the new compiled node : 
and i have this error : 
```
ylo2@ylo2-UP-WHL01:~/catkin_ws$ /home/ylo2/catkin_ws/devel/lib/wolf_ylo2_interface/ylo2_moteus_node
[ERROR]: PCANDevice::Open: Failed to Open PCANFD.: No such file or directory
[ERROR]: Unable to initialize CAN interface: PCAN_PCIBUS1
```
PCAN_PCIBUS1 to 4 are the correct port access name !

**Comment by elpimous** [comment]
here is an old working example of pcan working code : https://pastebin.com/R7Sk89bt
`Unable to initialize CAN interface: PCAN_PCIBUS1` perhaps type is wrong ?

**Comment by graiola** [comment]
Unfortunately I don't have a CAN interface to test on... sorry about that

**Comment by elpimous** [comment]
Hey, initializing working !! it was wrong ports calls : see mods on node.
