### ISSUE TITLE
Ament

### ISSUE THREAD

**Issue by graiola** [graiola/wolf_ylo2_interface#3]
Why do we need this extra build tool?

**Comment by elpimous** [comment]
Hello Gennaro. At home in 40minuts..Envoyé depuis mon téléphone Huawei-------- Message original --------De : Gennaro Raiola ***@***.***>Date : mer. 23 févr. 2022 à 14:50À : graiola/wolf_ylo2_interface ***@***.***>Cc : Subscribed ***@***.***>Objet : [graiola/wolf_ylo2_interface] Ament (Issue #3)
Why do we need this extra build tool?

**Comment by elpimous** [comment]
Why ament ? perhaps because it was a package for ros2, and it built messages and services !!

I didn't look on build files, and #rclcpp std_msgs sensor_msgs k3lso_msgs) are not needed anymore, i think

I commented each ament command in CMakefiles.txt

**Comment by graiola** [comment]
Wolf doesn't support ros2 yet, so ament could complicate the compilation... I would stick with catkin for the moment.

**Comment by elpimous** [comment]
Correct
