### ISSUE TITLE
imu return form

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf_ylo2_interface#4]
What is the best return form of the imu function, for Wolf_controller ?

- a simple list of 10 floats, with only 2 brackets ?
like  imu = {var1, var2, var3........var10}

**Comment by graiola** [comment]
the structure used in the controller is this one:

https://github.com/graiola/wolf_hardware_interface/blob/master/src/wolf_robot_hw.cpp#L73-L75

which are 3 vectors of double.

you can create a vector of 10 values and then copy the values to these vectors.

**Comment by elpimous** [comment]
hey, code working (without consideration to memory leaks risks, neither possible optimization) lol
But don't have success to convert : _void ex3_callback_data()_ to `std::vector<double> ex3_callback_data()` in order to return the vector(10)..
Need to investigate a bit more...

**Comment by elpimous** [comment]
hello, any help ?
i'd like to modify this function ; `void callback_data(void* context, int sensor_id, SensorData* sensor_data)`
it contents the vector `imu_feedback` that i'd like to return..
So I modified function type to :  `std::vector<double> callback_data(void* context, int sensor_id, SensorData* sensor_data)`
to be able to return `imu_feedback`
I encounter this error at compilation : `error: could not convert ‘imu_feedback.std::vector<double>::operator[](9)’ from ‘__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type’ {aka ‘double’} to ‘std::vector<double>’`
Any idea ?

**Comment by graiola** [comment]
Hi, could you point me the line? Also, I can not compile at all the master branch because of this array:

https://github.com/graiola/wolf_ylo2_interface/blob/master/include/wolf_ylo2_interface/ylo2_robot_hw.hpp#L27-L30

**Comment by elpimous** [comment]
Hi Gennaro.
 Regardind to imu error : 
https://github.com/graiola/wolf_ylo2_interface/blob/d723086364f3d1b6af32d1a7f9b9266c1c549f47/myahrs%2B/myahrs%2B_imu.hpp#L32
here is the target void function. (doesn't return anything)

need to change function type to another type to be able to return the imu vertor variable (to be callable in wolf_controller).

When changing type from void,to vector<double>, i have access to the vector return. However, changing type produces error with the myahrs+ lib, here : 
https://github.com/graiola/wolf_ylo2_interface/blob/d723086364f3d1b6af32d1a7f9b9266c1c549f47/myahrs%2B/myahrs_plus.hpp#L3051

here is the term message error : 

```
myahrs+$ make all
g++ -O2 -std=c++11   -c -o myahrs+_node.o myahrs+_node.cpp
In file included from myahrs+_node.cpp:1:
myahrs+_imu.hpp: In function ‘void Imu_data(const char*, int)’:
myahrs+_imu.hpp:56:35: error: invalid conversion from ‘std::vector<double> (*)(void*, int, WithRobot::SensorData*)’ to ‘void (*)(void*, int, WithRobot::SensorData*)’ [-fpermissive]
   56 |     sensor.register_data_callback(callback_data, &sample_counter);
      |                                   ^~~~~~~~~~~~~
      |                                   |
      |                                   std::vector<double> (*)(void*, int, WithRobot::SensorData*)
In file included from myahrs+_imu.hpp:10,
                 from myahrs+_node.cpp:1:
myahrs_plus.hpp:3051:43: note:   initializing argument 1 of ‘void WithRobot::MyAhrsPlus::register_data_callback(void (*)(void*, int, WithRobot::SensorData*), void*)’
 3051 |         void register_data_callback(void(*callback)(void* context, int sensor_id, SensorData* sensor_data), void* callback_context) {
      |                                     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [<commande interne> : myahrs+_node.o] Erreur 1
```

**Comment by elpimous** [comment]
You'll see the type i'd like, and the return, commented under TODO, in wolf_ylo2_interface/myahrs+/myahrs+_imu.hpp, L33-46
```
//TODO 
// std::vector<double> callback_data(void* context, int sensor_id, SensorData* sensor_data)
void callback_data(void* context, int sensor_id, SensorData* sensor_data)
{
    Quaternion& q = sensor_data->quaternion;
    ImuData<float>& imu = sensor_data->imu;

    // without magnet values, neither temp
    std::vector<double> imu_data = {q.x, q.y, q.z, q.w, imu.ax, imu.ay, imu.az, imu.gx, imu.gy, imu.gz};

    //TODO 
    // return (imu_data);
    std::cout << (imu_data[9]);
}
```

**Comment by elpimous** [comment]
About :  _Also, I can not compile at all the master branch because of this array:_

https://github.com/graiola/wolf_ylo2_interface/blob/master/include/wolf_ylo2_interface/ylo2_robot_hw.hpp#L27-L30_**

The map is wrong, because the file is the aliengo startup model...
I stupidly renamed aliengo parts as ylo2 ones...
see under original code parts : 

```
#include <aliengo_hal/aliengo_hal.h>

	...
	
          aliengohal::FL_0, aliengohal::FL_1, aliengohal::FL_2, // LF
```

**Comment by elpimous** [comment]
Should we better start with the gazebo_wolf_interface, to integrate ylo2_moteus_controller ?

**Comment by graiola** [comment]
The simulation interface is ok (it is the one you are using with gazebo). What we need is to wrap the moteus drivers in wolf_ylo2_interface.

**Comment by graiola** [comment]
> About : _Also, I can not compile at all the master branch because of this array:_
> 
> https://github.com/graiola/wolf_ylo2_interface/blob/master/include/wolf_ylo2_interface/ylo2_robot_hw.hpp#L27-L30_**
> 
> The map is wrong, because the file is the aliengo startup model... I stupidly renamed aliengo parts as ylo2 ones... see under original code parts :
> 
> ```
> #include <aliengo_hal/aliengo_hal.h>
> 
> 	...
> 	
>           aliengohal::FL_0, aliengohal::FL_1, aliengohal::FL_2, // LF
> ```

Can we remove this?

**Comment by elpimous** [comment]
Yes, I think so, if not needed by Wolf_controller...

**Comment by elpimous** [comment]
the big trick, i think, is `controller._motors[id]->` to automate motor ID to it can port !

**Comment by graiola** [comment]
> Yes, I think so, if not needed by Wolf_controller...

It was needed with aliengo to map the order of its joints with the order used in wolf.

> the big trick, i think, is `controller._motors[id]->` to automate motor ID to it can port !

I think this would replace the structure we had for aliengo.

**Comment by elpimous** [comment]
👍
https://github.com/graiola/wolf_ylo2_interface/issues/4#issuecomment-1054483708
Any idea of type I should use?
