### ISSUE TITLE
Erreur de segmentation (core dumped)

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf_ylo2_interface#6]

**Comment by elpimous** [comment]
the error, regarding to added std::cout in file tells me that error seems to happen here : 
https://github.com/graiola/wolf_ylo2_interface/blob/a6f28da7ae4195ff0965f326dcd4e80850ffcfdb/ylo2_moteus/src/moteus_pcan/moteus_pcan_interface.cpp#L110

**Comment by elpimous** [comment]
Well, i progress...
the error comes from the `ylo2_moteus_node main()`
those functions produce the error : 
```
  activate_torque_cmd(motor_id,true);
  send_tau(motor_id,1.0);
  activate_torque_cmd(motor_id,false);
```
Commenting them, here is the successed terminal return : 
```
ylo2@ylo2-UP-WHL01:~/catkin_ws$ /home/ylo2/catkin_ws/devel/lib/wolf_ylo2_interface/ylo2_moteus_node 02
opening pcan port : /dev/pcanpcifd0
initializing pcan port, from ID : 1
MoteusPcanInterface::is_initialized()
opening pcan port : /dev/pcanpcifd1
initializing pcan port, from ID : 4
MoteusPcanInterface::is_initialized()
opening pcan port : /dev/pcanpcifd2
initializing pcan port, from ID : 7
MoteusPcanInterface::is_initialized()
opening pcan port : /dev/pcanpcifd3
initializing pcan port, from ID : 10
MoteusPcanInterface::is_initialized()
Selected motor_id: 2
Motors initialized and stopped !
testing MoteusPcanInterface::loop()
testing MoteusPcanInterface::status_loop()
testing MoteusPcanInterface::loop()
testing MoteusPcanInterface::status_loop()
testing MoteusPcanInterface::loop()
testing MoteusPcanInterface::status_loop()
testing MoteusPcanInterface::loop()
MoteusPcanInterface::is_running()
MoteusPcanInterface::is_running()
MoteusPcanInterface::is_running()
testing MoteusPcanInterface::status_loop()MoteusPcanInterface::is_running()
Motors are running !!!

testing MoteusPcanInterface::stop()
testing MoteusPcanInterface::stop()
testing MoteusPcanInterface::stop()
testing MoteusPcanInterface::stop()
Motors stopped
```

**Comment by elpimous** [comment]
i think that the seg fault comes from: 
https://github.com/graiola/wolf_ylo2_interface/blob/9efc58a3cbdb4cf947ab9ec7d8320ca536f99726/ylo2_moteus/src/ylo2_moteus_node.cpp#L69

when uncommenting the first main() function `activate_torque_cmd(motor_id,true);` I think that map isn't well structured ?!

**Comment by elpimous** [comment]
Need to check exactly what it does : `controller._motors[motor_id]->XXX`

**Comment by graiola** [comment]
Try the branch fix_segfault

**Comment by elpimous** [comment]
hi. Branch tested : 
with only this function activated in main() : `_controller->stop();`

```
ylo2@ylo2-UP-WHL01:~/catkin_ws$ /home/ylo2/catkin_ws/devel/lib/wolf_ylo2_interface/ylo2_moteus_node
opening pcan port : /dev/pcanpcifd0
opening pcan port : /dev/pcanpcifd1
opening pcan port : /dev/pcanpcifd2
opening pcan port : /dev/pcanpcifd3
All ports correctly activated !
TEST
Usage: /home/ylo2/catkin_ws/devel/lib/wolf_ylo2_interface/ylo2_moteus_node motor_id

```
It's working !!


but with this function : `activate_torque_cmd(motor_id,true);` or one else, asking the map : 

```
ylo2@ylo2-UP-WHL01:~/catkin_ws$ /home/ylo2/catkin_ws/devel/lib/wolf_ylo2_interface/ylo2_moteus_node 2
opening pcan port : /dev/pcanpcifd0
opening pcan port : /dev/pcanpcifd1
opening pcan port : /dev/pcanpcifd2
opening pcan port : /dev/pcanpcifd3
All ports correctly activated !
TEST
Selected motor_id: 2
Motors initialized and stopped !
Motors are running !!!
Erreur de segmentation (core dumped)
ylo2@ylo2-UP-WHL01:~/catkin_ws$
```

**Comment by elpimous** [comment]
hello Gennaro. New debug tests with "cout"
```
void MoteusPcanInterface::status_loop(){
    //std::cout << "testing MoteusPcanInterface::status_loop()" << std::endl;
    while(true){
        std::cout << "here 33" << std::endl;
        for(int i=0; i<10; i++){
            std::cout << "here 34" << std::endl;
            **std::this_thread::sleep_for(std::chrono::milliseconds(100));**
            std::cout << "here 34.5" << std::endl;
            if(!_running){
                std::cout << "here 35" << std::endl;
                return;
            }
        }
        std::cout << "here 35.5" << std::endl;
        {
            std::lock_guard<std::mutex> guard(_freq_counter_mutex);
            _freq = _freq_counter;
            _freq_counter = 0;
            std::cout << "here 36" << std::endl;
        }
    }
}
```

**Comment by elpimous** [comment]
Also, i think there is a problem here..
in the original file, there are 12 different address (one for motor, because Robin robot has 3 Pcan boards, so one motor on one port)
```
std::vector<MotorInfo> motors_info = {
    // Front Right
    {"torso_to_abduct_fr_j",    "/dev/pcan-pcie_fd/devid=18", 1,  -0.00, true}, // Hip
    {"abduct_fr_to_thigh_fr_j", "/dev/pcan-pcie_fd/devid=12", 2,  0.92, true}, // Leg
    {"thigh_fr_to_knee_fr_j",   "/dev/pcan-pcie_fd/devid=11", 3,  -1.483529864, true}, // Low Leg
    // Front Left
    {"torso_to_abduct_fl_j",    "/dev/pcan-pcie_fd/devid=20", 4,  -0.00, true}, // Hip
    {"abduct_fl_to_thigh_fl_j", "/dev/pcan-pcie_fd/devid=10", 5,  0.92, false}, // Leg
    {"thigh_fl_to_knee_fl_j",   "/dev/pcan-pcie_fd/devid=13", 6,  -1.483529864, false}, // Low Leg
    // Rear Right
    {"torso_to_abduct_hr_j",    "/dev/pcan-pcie_fd/devid=19", 10, -0.00, false}, // Hip
    {"abduct_hr_to_thigh_hr_j", "/dev/pcan-pcie_fd/devid=15", 11, 1.047197551, true}, // Leg
    {"thigh_hr_to_knee_hr_j",   "/dev/pcan-pcie_fd/devid=17", 12, -1.483529864, true}, // Low Leg
    // Rear Left
    {"torso_to_abduct_hl_j",    "/dev/pcan-pcie_fd/devid=21", 7,  -0.00, false}, // Hip
    {"abduct_hl_to_thigh_hl_j", "/dev/pcan-pcie_fd/devid=14", 8,  1.047197551, false}, // Leg
    {"thigh_hl_to_knee_hl_j",   "/dev/pcan-pcie_fd/devid=16", 9,  -1.483529864, false}  // Low Leg
};

MoteusInterfaceMotorsMap interface_motors_map = {
    {"/dev/pcan-pcie_fd/devid=18", {1}}, // Hip FR
    {"/dev/pcan-pcie_fd/devid=12", {2}}, // Leg FR
    {"/dev/pcan-pcie_fd/devid=11", {3}}, // Low Leg FR
    {"/dev/pcan-pcie_fd/devid=20", {4}}, // Hip FL
    {"/dev/pcan-pcie_fd/devid=10", {5}}, // Leg FL
    {"/dev/pcan-pcie_fd/devid=13", {6}}, // Low Leg FL
    {"/dev/pcan-pcie_fd/devid=19", {10}}, // Hip RR
    {"/dev/pcan-pcie_fd/devid=15", {11}}, // Leg RR
    {"/dev/pcan-pcie_fd/devid=17", {12}}, // Low Leg RR
    {"/dev/pcan-pcie_fd/devid=21", {7}}, // Hip RL
    {"/dev/pcan-pcie_fd/devid=14", {8}}, // Leg RL
    {"/dev/pcan-pcie_fd/devid=16", {9}}  // Low Leg RL
};
```

on our code, we have same address for 3 motors, each time, and it's correct !
https://github.com/graiola/wolf_ylo2_interface/blob/dd39f59733aa8980c498be83707e3f850e0c0235/ylo2_moteus/src/ylo2_moteus_node.cpp#L30-L61

**Comment by elpimous** [comment]
however, the control motor loop  leaves when it sees same adress, so it only activates 4 motors (1,4,7,10)
here : https://github.com/graiola/wolf_ylo2_interface/blob/dd39f59733aa8980c498be83707e3f850e0c0235/ylo2_moteus/src/moteus_pcan/moteus_pcan_motor.cpp#L13
id should cycle from 1 to 12 ! here, only 1,4,7,10 (the first motor for each different pcan adress)

**Comment by elpimous** [comment]
Hello @graiola .. good news, 
I think that the problem comes from the interface_map !! 
The code activates port and memorize the ID, but when it sees another time, the same port, it pass...
This is why i only saw activated id 1,4,7,10 !! (the first one of each new port)
so, i restarted with devel branch (fix_segfault caused errors),
modified both maps : https://github.com/graiola/wolf_ylo2_interface/blob/265ee30f1c4a8062008a7980184a3da2722adcf9/ylo2_moteus/src/ylo2_moteus_node.cpp#L21-L38
modified main() : https://github.com/graiola/wolf_ylo2_interface/blob/265ee30f1c4a8062008a7980184a3da2722adcf9/ylo2_moteus/src/ylo2_moteus_node.cpp#L102-L120

and working !!!! for one motor only for now ! need to change motors map reading, i think.
```
ylo2@ylo2-UP-WHL01:~/catkin_ws$ /home/ylo2/catkin_ws/devel/lib/wolf_ylo2_interface/ylo2_moteus_node 2
Selected motor_id: 2
Motors are running !!!
Motor 2, torque enabled
Position : -0.0711536
velocity : -0.00089407
torque : 0
Motor 2, torque disabled
ylo2@ylo2-UP-WHL01:~/catkin_ws$ 
```

**Comment by graiola** [comment]
That's good news! :)

Next I would try to create some code to write and read the torques to check the quality of the tracking.

**Comment by elpimous** [comment]
OK, cool
Please comment code, for my anderstanding..
(I like to know how it works)
Tell me test process, and what you need.
Ready to test, safety.

**Comment by elpimous** [comment]
Sdk kit ready.. 
![Uploading IMG_20220306_124617.jpg…]()

**Comment by elpimous** [comment]
Hey, need help : 
as you know, the interface map calls doesn't work as expected : 
https://github.com/graiola/wolf_ylo2_interface/blob/5afdf60052e1b896adb73c7c2c410c766a9fc521/ylo2_moteus/src/ylo2_moteus_node.cpp#L50-L60

when running, it call only reports id's 1, 4, 7, 10.

I think that error could be due to the fact that the code passes the loop, when it sees a second time, the same port.

I hardly searched, and tested many things, but i cant find the origine of this "loop". Could you help, here ?

The devel branch is the good start search.

could it be this method ? https://github.com/graiola/wolf_ylo2_interface/blob/5afdf60052e1b896adb73c7c2c410c766a9fc521/ylo2_moteus/src/moteus_pcan/moteus_pcan_controller.cpp#L4-L8

**Comment by graiola** [comment]
Can you try this structure?

```
MoteusInterfaceMotorsMap interface_motors_map = {
  {"PCAN_PCIBUS1", {1,2,3}}  ,
  {"PCAN_PCIBUS2", {4,5,6}}  ,
  {"PCAN_PCIBUS3", {7,8,9}}  ,
  {"PCAN_PCIBUS4", {10,11,12}}
};
```

**Comment by elpimous** [comment]
@graiola ..
partially Working !!!
opening specific issue !
