### ISSUE TITLE
seg fault with interface_motors_map

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf_ylo2_interface#7]
Well, after many tests, with calls on id = 99 : 
command : `/home/ylo2/catkin_ws/devel/lib/wolf_ylo2_interface/ylo2_moteus_node 99`
```
MoteusInterfaceMotorsMap interface_motors_map = {

  {"/dev/pcanpcifd0", {1}},
  {"/dev/pcanpcifd1", {99}},
  {"/dev/pcanpcifd2", {7}},
  {"/dev/pcanpcifd3", {10}}
};
```
**works !**

```
  {"/dev/pcanpcifd0", {1, 2, 3}},
  {"/dev/pcanpcifd1", {4, 5, 6, 99}},
  {"/dev/pcanpcifd2", {7, 8, 9}},
  {"/dev/pcanpcifd3", {10, 11, 12}}
```
**Doesn't work !! seg fault**

**Comment by graiola** [comment]
I am not following, does it work as expected or not? what does 99 represent?

**Comment by elpimous** [comment]
"99" is the id of the sdk motor (this way,  i can test what i want without risks of legs crashs.
ylo2 motors are 1-12, and the 13th one is 99, connected to /dev/pcanpcifd1)

Strange, it partially works : i can run a main() with each target motor, but the main doesn't end.
Sure, this map can read all motors. Before, it crashed.

But now, the main() doesn't end.
The debugger tells me that it's a segmentation fault ! 
Think that the {x,y,z} isn't correctly parsed.

Question : do you see what function read interface_motors_map values and parse them ? Can't find it !
I'd like to anderstand it.
Thanks Gennaro

**Comment by elpimous** [comment]
Humm, seems happening here.
https://github.com/graiola/wolf_ylo2_interface/blob/377b952d684e40faf78811608e7345203adf1268/ylo2_moteus/src/moteus_pcan/moteus_pcan_interface.cpp#L104-L111

**Comment by graiola** [comment]
I committed a possible bug fix here:

https://github.com/graiola/wolf_ylo2_interface/tree/fix_stop_segfault

Also, I changed the scoped locks with atomics and removed .vscode since it should not be in the git repository :)

Let me know if it works because I can not run it with the motors.

**Comment by elpimous** [comment]
Hi Gennaro.  The loop doesn't stop, so the main() doesn't exit.
However, no error on Visual studio code debugger.!
I can access to each servo, but the loop doesn't stop !
Searching on that.....

**Comment by graiola** [comment]
Maybe you can try adding a signal handler.

**Comment by elpimous** [comment]
Hi @graiola 
after lot of tests, learning, lol, i know the origin ofthe error !
it's here : https://github.com/graiola/wolf_ylo2_interface/blob/12502d2d598530135c079a0019194a2040a3d11e/ylo2_moteus/src/moteus_pcan/moteus_pcan_interface.cpp#L102

without this line, the code works, and exit with an error : 
```
ylo2@ylo2-UP-WHL01:~/catkin_ws$ /home/ylo2/catkin_ws/devel/lib/wolf_ylo2_interface/ylo2_moteus_node 11
Selected motor_id: 11
Motors are running !!!
Motor 11, torque enabled
Position : -0.0244268
velocity : -0.0196759
torque : 0
Motor 11, torque disabled
terminate called without an active exception
Abandon (core dumped)
```
with the line uncommented, no error, but program blocks.

**Comment by graiola** [comment]
Hi @elpimous any news?

**Comment by elpimous** [comment]
Hi @graiola.
I corrected a bad can message build.
Now I have correct pos, vel, fftorque, on a small 12 bytes frame length. 

Always fighting with the strange loop lock..
Sometimes it works, sometimes it locks.
The problems must come from the loop() function.... A mutex problem?!!.
Searched on web, nut not certain how to use signal handler calls

But I can test motors the major part of time. Lol

Working on functions to send to each motor, with wolf_controller vector command variable.

Doing same for queries..

Did you progress on your code for torque performance test, to make me test.

Ps : in a near futur, if I can't correct the occasional lock of the controller loop(), I'll have to create a simpler code...
Ps2: I'll receive tomorrow a rplidar A2, to test with WoLF navigation... Cool
Impatient to read you.
Vincent

**Comment by elpimous** [comment]
here is a function to query all motors and return a vector.
https://github.com/graiola/wolf_ylo2_interface/blob/8f7a473fd27d3fe6618eceb510f9459feb67c9be/ylo2_moteus/src/ylo2_moteus_node.cpp#L37-L53
Could you confirm the correct structure of it return for Wolf usage ?!

Could I improve the read() function, in term of memory ??

**Comment by graiola** [comment]
I think the query function is enough, we just have to call it with with a motor_id+1. This is how the read function is implemented for aliengo: https://github.com/graiola/wolf_aliengo_interface/blob/master/src/aliengo_robot_hw.cpp#L82-L112

if you want to improve the global_query function in terms of memory, you should not allocate the vector inside it, instead allocate it externally and then pass it to the function by reference.

**Comment by elpimous** [comment]
Modified with query option.
used references ( i hope to be correct, but it works lol)
Added imu feedback
