### ISSUE TITLE
use simulation to test a real motor 

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf_ylo2_interface#8]
Hello, could i use simulation to add real motors orders in readSim() and writeSim() simulation functions (under wolf_gazebo_interface ?) ?
So, using the `roslaunch wolf_description_utils standalone.launch` gui, same time as `roslaunch wolf_controller wolf_controller_bringup.launch`, i could use sliders to test real motors positions, and rotation ?!

I'd like to limit torque, for security. Where can i limit it ? or just use a divider,  anything like torque/10?

**Comment by graiola** [comment]
you can use the `test_hardware.launch` in the `devel` branch to visualize the joints and trunk position (calculated from the imu), but we need to connect the controller manager to the real hardware (both joints and imu).

**Comment by elpimous** [comment]
working, thanks
