### ISSUE TITLE
impedance_controller

### ISSUE THREAD

**Issue by graiola** [graiola/wolf_ylo2_interface#9]
Salut @elpimous ,

can you try the last push on the controller branch? I reorganized the code and fixed the undefined reference issue. Lmk if it works on your side as well! :)

**Comment by elpimous** [comment]
Thanks for update..
Working without errors, but when moving real leg, i don't see any change on rviz...
my query function must be wrong...
Working on it

**Comment by elpimous** [comment]
Hello, 
Query, send_tau and stop commands work !
1/ About query : i can move real robot legs and see moves on rviz, but wrong directions/positions ! Where could I change those params ?
2/ About send_tau : how to test tau on test_hardware.launch ? Use a motor angle in a topic ?
Best.
Vincent

**Comment by graiola** [comment]
Hi Vincent,

that's good news! 
1) You could create a map with signs for each motor, similar to what was done here for aliengo: https://github.com/graiola/wolf_aliengo_interface/blob/master/include/wolf_aliengo_interface/aliengo_robot_hw.hpp#L45-L51
2) I think it would be useful to create an impedance controller that receives a joint angle and moves the motors accordingly with the torque generated.

**Comment by elpimous** [comment]
for servos order, it works great !
```
  // @brief Map Ylo2 internal joint indices to WoLF joints order
  std::array<unsigned int, 12> ylo2_motor_idxs_
          {{
          1, 2, 3,    // LF
          7, 8, 9,    // LH
          4, 5, 6,    // RF
          10, 11, 12, // RH
          }};
```
Also, I changed some inverse rotations motors, on code.
Query works perfectly.

**Comment by elpimous** [comment]
using joint_state sliders on test_hardware.launch, doesn't affect joints rotations on rviz. Is it normal ?
It should make my real joints moving too ?
(i must say that i don't know how to build an impedance controller !)

For now, everything work nicely !
i tested a send tau with a defined value, and it works !
```
void ylo2RobotHw::write()
{
  for (unsigned int jj = 0; jj < n_dof_; ++jj)
    {
      send_tau(ylo2_motor_idxs_[jj], 1.0); // testing tau to all motors, OK
      //std::cout << jj+1 << "tau = " << static_cast<float>(joint_effort_command_[jj]) << std::endl;
    }
}
```
Think that the next step is test tau in test_hardware.launch,
and after, test walk cinematic, robot in the air.

Could you tell me your mind ?
if you have small time, could you help me to test tau in test_hardware.launch ?

**Comment by graiola** [comment]
> using joint_state sliders on test_hardware.launch, doesn't affect joints rotations on rviz. Is it normal ? It should make my real joints moving too ? (i must say that i don't know how to build an impedance controller !)

No, unfortunately it is not supposed to make the motors spin.

> Think that the next step is test tau in test_hardware.launch, and after, test walk cinematic, robot in the air.
> 
> Could you tell me your mind ? if you have small time, could you help me to test tau in test_hardware.launch ?

Sure, I can try to implement something :)

**Comment by elpimous** [comment]
👍😋

**Comment by graiola** [comment]
@elpimous I will be working on it in the next days

**Comment by elpimous** [comment]
👍😍

**Comment by graiola** [comment]
@elpimous Can you try the `motor_adapter` branch? 

https://github.com/graiola/wolf_ylo2_interface/blob/motor_adapter/src/ylo2_robot_hw.cpp#L23-L40

I created a structure to hold the index, sign and reduction for each motor. Lmk if it works.
Also I added an option to perform a dry run, `dry_run` and added the `joint_trajectory_controller` to run an impedance.

**Comment by elpimous** [comment]
Working nice !!!

**Comment by graiola** [comment]
You can try the `joint_trajectory_controller` to send commands to the joints. Did you try that?

Here are the parameters for it:
https://github.com/graiola/wolf_ylo2_interface/blob/motor_adapter/params/joint_trajectory_controller.yaml

and you can interact with it with this interface once you have it running:
http://wiki.ros.org/rqt_joint_trajectory_controller

I added this node to the launch file on the `motor_adapter` branch.

**Comment by elpimous** [comment]
Humm, playing with sliders should move legs under rviz, or real robot ? It doesn't !
And moving real robot doesn't move sliders, too

**Comment by elpimous** [comment]
![IMG_20220429_001044](https://user-images.githubusercontent.com/8529940/165856474-23a7f391-29e0-4e37-ad35-bcb260d39bfd.jpg)

**Comment by elpimous** [comment]
but present interface values correspond to actual motors real position. (perhaps just missing a loop ?)
Perhaps should I test with **dry_run** activated ?

**Comment by graiola** [comment]
Did you try to change the pid gains? Also, moving the joints on the robot, does it cause the robot in rviz to move or not?

**Comment by elpimous** [comment]
moving the joints on the robot, does it cause the robot in rviz to move or not?
Yes, correct direction, Id, and factor (thanks to your mod.)

Did you try to change the pid gains
No. (what should I observe, changing p, or d...)

**Comment by graiola** [comment]
- did you install the `joint_trajectory_controller`? 

- do you have any error on the terminal?

- are the joint values in the sliders correct?

**Comment by elpimous** [comment]
Of course
(just  imu error, because I removed myahrs Catkin package, to be able to catkin_make) 
Yes

**Comment by graiola** [comment]
Of course it does not work! We commented this line: https://github.com/graiola/wolf_ylo2_interface/blob/motor_adapter/src/ylo2_robot_hw.cpp#L149-L150

**Comment by elpimous** [comment]
Cool.. Exciting (trying tonight..)
Any risks with motor moves?

**Comment by graiola** [comment]
I would lower all the gains before attempting a motion with the sliders.

**Comment by elpimous** [comment]
I can lower the max torque in can frame, to limit force.. Anything like max torque 1.5

**Comment by elpimous** [comment]
Humm, strange ! 
After a new catkin_make clean & catkin_make on the motor_adapter branch (fresh version, with git pull origin motor_adapter)
the launch let me see a rviz frame error on robot parts !! It worked yesterday, and now, it produce this error on all branch tests.
Only on legs !!
wolf_description has been tested, and i did a git fetch & git pull for secure.
here is the terminal, without errors : https://pastebin.com/ZW4kkzKL
and a screeshot of rviz:
[](url)

**Comment by elpimous** [comment]
![Uploading IMG_20220429_230939.jpg…]()

**Comment by elpimous** [comment]
![IMG_20220429_230939](https://user-images.githubusercontent.com/8529940/166071200-f66abf92-26ce-4b52-b088-62fb14c0f9b0.jpg)

**Comment by elpimous** [comment]
morever, it seems that, after a ubuntu upgrade, that a package has updated !
`Aucune règle pour fabriquer la cible « /usr/lib/x86_64-linux-gnu/libignition-msgs5.so.5.8.1 », nécessaire pour « /home/ylo2/catkin_ws/devel/lib/libRealsenseGazeboPlugin.so ». Arrêt.`

**Comment by graiola** [comment]
hmm I think it is related to the fact that there is nobody publishing the world frame ( usually it is the wolf_controller doing so )

**Comment by elpimous** [comment]
Humm OK... Searching..

**Comment by elpimous** [comment]
Well, ok. Error seems coming from input/output can frame,  even if can frames are well formatted) ..  It put some controllers into error. 
Investigating.... I'll tell you
